# Generated by Django 2.2.1 on 2019-05-16 11:28

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_cvbin_cvgroups_filebin'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebin',
            name='filename',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='filebin',
            name='path',
            field=models.FileField(upload_to=project.models.get_member_upload_to),
        ),
    ]
