# Generated by Django 2.2.1 on 2019-05-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190516_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebin',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
