# Generated by Django 2.2.1 on 2019-05-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
