# Generated by Django 2.2.1 on 2019-05-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_foldercolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebin',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='filebin',
            name='file_hash',
            field=models.CharField(default=0, max_length=256),
        ),
        migrations.AddField(
            model_name='filebin',
            name='is_delted',
            field=models.BooleanField(default=0),
        ),
    ]
