# Generated by Django 2.2.1 on 2019-05-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190521_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebin',
            name='email',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='filebin',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
