# Generated by Django 2.2.1 on 2019-05-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20190521_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebin',
            name='applicant',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='filebin',
            name='cv_updated',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
