# Generated by Django 2.2.1 on 2019-05-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20190521_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filebin',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='cvgroups',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='cvgroups',
            name='path',
        ),
        migrations.RemoveField(
            model_name='cvgroups',
            name='title',
        ),
        migrations.AddField(
            model_name='cvgroups',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.FileBin'),
        ),
        migrations.CreateModel(
            name='cvcombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.CharField(max_length=256, null=True)),
                ('is_delted', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Cvbin')),
            ],
        ),
        migrations.AddField(
            model_name='cvgroups',
            name='combination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.cvcombination'),
        ),
    ]
